server.port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phonebook
    username: root
    password: changeme
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug