version: '3'

services:

  database:
    image: mysql
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: phonebook
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - phonebook-network
    volumes:
      - database-data:/var/lib/mysql
  phonebook:
    depends_on:
      - database
    image: phonebook:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - phonebook-network
volumes:
  database-data:

networks:
  phonebook-network:
    driver: bridge
